name: Build and Publish Production Image

on:
  push:
    branches: [ "main" ]

jobs:

  deploy-prod:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build . --file Dockerfile-prod --tag aeroz:prod

    - name: Log in to Docker registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login registry.silvy-leligois.fr -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Tag Docker image for registry
      run: docker tag aeroz:prod registry.silvy-leligois.fr/aeroz:prod

    - name: Push Docker image to registry
      run: docker push registry.silvy-leligois.fr/aeroz:prod

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PROD_HOST }}
        username: ${{ secrets.PROD_USERNAME }}
        port: ${{ secrets.PROD_PORT }}
        password: "${{ secrets.PROD_PASSWORD }}"
        script: "cd /home/debian/docker/aeroz && ./deploy.sh"
