name: tests

on:
  pull_request:
    branches:
      - develop
      - main
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Duster Lint"
        uses: tighten/duster-action@v3
        with:
          args: lint

  ci:
    runs-on: ubuntu-latest
    environment: Testing
    env:
      APP_ENV: testing
      APP_KEY: base64:SnTWY8YvmGWLa4zrZEy1iFqdcYHl58AT2f+2crH1BIA=
      DB_CONNECTION: pgsql
      DB_HOST: localhost
      DB_PASSWORD: postgres
      DB_USERNAME: postgres
      DB_DATABASE: postgres
      APP_LOCALE: fr
      APP_URL: http://localhost
      MAPBOX_KEY: fake-key-for-testing

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: xdebug

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Node Dependencies
        run: npm i

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Create Environment File
        run: |
          echo "APP_NAME=Laravel" > .env
          echo "APP_ENV=testing" >> .env
          echo "APP_KEY=base64:SnTWY8YvmGWLa4zrZEy1iFqdcYHl58AT2f+2crH1BIA=" >> .env
          echo "APP_DEBUG=true" >> .env
          echo "APP_TIMEZONE=UTC" >> .env
          echo "APP_URL=http://localhost" >> .env
          echo "APP_LOCALE=fr" >> .env
          echo "DB_CONNECTION=pgsql" >> .env
          echo "DB_HOST=localhost" >> .env
          echo "DB_PORT=${{ job.services.postgres.ports[5432] }}" >> .env
          echo "DB_DATABASE=postgres" >> .env
          echo "DB_USERNAME=postgres" >> .env
          echo "DB_PASSWORD=postgres" >> .env
          echo "CACHE_STORE=array" >> .env
          echo "SESSION_DRIVER=array" >> .env
          echo "QUEUE_CONNECTION=sync" >> .env
          echo "MAIL_MAILER=array" >> .env
          echo "MAPBOX_KEY=fake-key-for-testing" >> .env

      - name: Build Assets
        run: npm run build

      - name: Run Database Migrations
        run: php artisan migrate --force
        env:
          DB_PORT: ${{ job.services.postgres.ports[5432] }}

      - name: Clear Application Cache
        run: |
          php artisan config:clear
          php artisan cache:clear
          php artisan view:clear

      - name: Run Tests
        run: ./vendor/bin/pest --coverage --min=100
        env:
          DB_PORT: ${{ job.services.postgres.ports[5432] }}
          APP_URL: http://localhost
          XDEBUG_MODE: coverage
